"""Shared test setup for the portable agent package."""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
OFFLINE_CONFIG_ROOT = PACKAGE_ROOT / ".wxo-local-config"

# The ADK hard-codes ~/.config/orchestrate as a function default at import
# time. Redirect only that Config class for offline tests; do not change HOME.
from ibm_watsonx_orchestrate_core.utils import config as adk_config

adk_config.DEFAULT_CONFIG_FILE_FOLDER = str(OFFLINE_CONFIG_ROOT / "config")
adk_config.AUTH_CONFIG_FILE_FOLDER = str(OFFLINE_CONFIG_ROOT / "cache")
adk_config.Config.__init__.__defaults__ = (
    adk_config.DEFAULT_CONFIG_FILE_FOLDER,
    adk_config.DEFAULT_CONFIG_FILE,
)

if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))


def pytest_sessionfinish(session: object, exitstatus: int) -> None:
    """Remove only the disposable ADK config generated by offline imports."""

    shutil.rmtree(OFFLINE_CONFIG_ROOT, ignore_errors=True)
